const Routes = {
	HOME_STACK: "HOME_STACK", // HOMESTACK CONTAINER FOR TABS
	HOME_TABS: "HOME_TABS", //HOME TABS
    FEED_SCREEN:"FEED",
    HOME_SCREEN: "HOME",
    OFFICIAL_SCREEN : "OFFICIAL",
    KERANJANG_SCREEN : "KERANJANG",
    AKUN_SCREEN :"AKUN"
	
};

export default Routes;